rummi/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from tenda.views import RegisterUserView,LoginView,LogoutView
from tenda import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^$', views.buscar, name='buscar'),
    url(r'^filtra',views.filtra,name='filtra'),
    url(r'^search_category', views.search_category, name='search_category'),
    url(r'^create_product', views.create_product, name='create_product'),
    url(r'^product_list/$', views.product_list, name='product_list2'),
    url(r'^product_list/(?P<product_id>\d+)/edit/$', views.edit_product, name='edit_product2'),
    url(r'^product_list/(?P<product_id>\d+)/eliminate/$', views.delete_product, name='eliminate_product2'),
    
	#Payment
    url(r'^payment$', views.payment, name='payment'),
    url(r'^payment_last$', views.payment, name='payment_last'),

    url(r'^payment/success$', views.success_payment, name='success_payment'),
    url(r'^payment/canceled$', views.unsuccess_payment, name='unsuccess_payment'),

    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^tickets$',views.tickets_list,name='tickets_list'),
    
    
    url(r'^product/(?P<id_product>\d+)',views.product, name='product'),
    url(r'^profile', views.profile_edit, name='profile'),
    #Cart
    url(r'^cart$', views.cart_list, name='cart'),
    url(r'^cart/add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^cart/remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
    
    #Admin zone
    url(r'^admin/$', views.admin_zone, name='admin_zone'),
    url(r'^admin/user_list/$', views.admin_zone_user_list, name='admin_zone_user_list'),
    url(r'^admin/user_list/(?P<user_id>\d+)/edit/$', views.admin_zone_edit_user, name='edit_users'),
    url(r'^admin/user_list/(?P<user_id>\d+)/eliminate/$', views.admin_zone_eliminate_user, name='eliminate_users'),
    url(r'^admin/user_list/create/$', views.admin_zone_create_users, name='create_users'),
    url(r'^admin/product_list/$', views.admin_zone_product_list, name='product_list'),
    url(r'^admin/product_list/(?P<product_id>\d+)/edit/$', views.admin_zone_edit_product, name='edit_product'),
    url(r'^admin/product_list/(?P<product_id>\d+)/eliminate/$', views.admin_zone_eliminate_product, name='eliminate_product'),
    url(r'^admin/product_list/create/$', views.admin_zone_create_product, name='admin_create_product'),
    url(r'^admin/payments_list/$', views.admin_zone_payments_list, name='payments_list'),

    url(r'^login', view=LoginView.as_view(),name='login'),
    url(r'^logout', views.logout_session, name='logout'),
    url(r'^registre', view=RegisterUserView.as_view(), name='registre'),
    url(r'^resultats_consulta', views.resultats_consulta, name='resultats_consulta.html'),
    url(r'^anunci', views.anunci, name='anunci.html'),
    url(r'^ajuda', views.ajuda, name='ajuda.html'),
    



] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tenda/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from paypal.standard.models import ST_PP_COMPLETED
from paypal.standard.ipn.signals import valid_ipn_received,invalid_ipn_received

def show_me_the_money(sender, **kwargs):
    ipn_obj = sender
    print ipn_obj.address_name
    print ipn_obj.address_country
    print ipn_obj.receiver_email
    print ipn_obj.residence_country
    print ipn_obj.payment_status
    for e in kwargs:
		print e
    user = kwargs.get('instance',None)
    #if ipn_obj.payment_status == ST_PP_COMPLETED:
	#u = UserProfile.objects.get(id=user.id)
    print user
  

valid_ipn_received.connect(show_me_the_money) 
# Create your models here.
def get_image_path(instance, filename):
    return os.path.join('fotos', str(instance.id), filename)
    
class Product(models.Model):
	name = models.CharField(max_length=100)
	description = models.CharField(max_length=500)
	price = models.DecimalField(max_digits = 8,decimal_places = 2)
	#avatar = models.ImageField(upload_to=get_image_path, null=True)
	data = models.DateTimeField(auto_now_add=True)
	is_buyed = models.BooleanField(default=False)

def get_image_filename(instance, filename):
    title = instance.post.title
    slug = slugify(title)
    return "post_images/%s-%s" % (slug, filename) 

class Images(models.Model):
    post = models.ForeignKey(Product)
    image = models.ImageField(upload_to=get_image_path,verbose_name='Image')
class UserProfile(models.Model): 
	username=models.CharField(max_length=100)
	email = models.CharField(max_length=100)
	password = models.CharField(max_length=100)
	province= models.CharField(max_length=100)
	postalnumber = models.IntegerField()

class Category(models.Model):
	name = models.CharField(max_length=100)
	
class Bill(models.Model):
	data = models.DateTimeField(auto_now=True, auto_now_add=False)
	adress = models.CharField(max_length=100)
	city = models.CharField(max_length=100)
	total = models.DecimalField(max_digits = 8,decimal_places = 2)
	class Meta:
		ordering =['data']
class Admin(models.Model):
	user = models.ForeignKey(UserProfile, on_delete=models.CASCADE, null=True)

class Publish(models.Model):
	user = models.ForeignKey(UserProfile, on_delete=models.SET_NULL, related_name='fk_product_user', null=True)
	product = models.ForeignKey(Product, on_delete=models.SET_NULL, related_name='fk_product_user', null=True)

class Owns(models.Model):
	category = models.ForeignKey(Category, on_delete=models.SET_NULL, related_name='fk_product_category', null=True)
	product = models.ForeignKey(Product, on_delete=models.SET_NULL, related_name='fk_product_category', null=True)
	
class Pay(models.Model):
	product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
	user = models.ForeignKey(UserProfile, on_delete=models.SET_NULL, null=True)
	bill = models.ForeignKey(Bill, on_delete=models.SET_NULL, null=True)
	
	

tenda/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth import login, authenticate,logout
from django.contrib.auth.models import User
from django.shortcuts import render,redirect,get_object_or_404
from django.template.loader import render_to_string
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect,HttpResponse,HttpResponseForbidden
from django.contrib.auth.decorators import login_required,user_passes_test
from django.views.generic import CreateView,View
from django.db.models import Q
from django import forms
from .forms import Consultaform,SignUpForm,RegisterForm,LoginForm,ProductForm,ProfileForm,CartAddProductForm,ProductEditForm,PaymentForm,Filtresform
from paypal.standard.forms import PayPalPaymentsForm
from .models import Product,UserProfile,Publish,Owns,Category,Pay,Bill,Images
from paypal.standard.models import ST_PP_COMPLETED
from paypal.standard.ipn.signals import valid_ipn_received
from django.conf import settings
from django.contrib import messages
import urllib,os,time
from cart import Cart




# Create your views here.
def admin_zone(request):
	#Imprimeix la pagina del administrador
	return render(request,'admin/admin.html')

# Aquesta view s'encarrega de crear el usuaris, regit pel el administrador
def admin_zone_create_users(request):
	
	if request.method =='POST':
			form = RegisterForm(request.POST)
			if form.is_valid():
				user = form.save(commit=False)
				#Agafem les dades de usuari i les guardem
				user.set_password(form.cleaned_data['password'])
				un = form.cleaned_data['username']
				em = form.cleaned_data['email']
				pas = form.cleaned_data['password']
				pro = form.cleaned_data['province']
				cp = form.cleaned_data['cp']
				#Comprobem que no existeixi un usuari amb el mateix nom
				data = UserProfile.objects.filter(username=un)
				
				if not data :
					print "No hi ha user amb el mateix nom"
					new_data = UserProfile.objects.create(username=un, email=em, password = pas,province=pro, postalnumber=cp)
					user.save()
					
				else:
					return HttpResponse("There are a user with the same username")
			return redirect('admin_zone_user_list')
	else:
		form = RegisterForm()
		return render(request,'admin/admin_zone_create_user.html',{'form': form })
		

#Aquesta view s'encarrega de editar les dades del usuari, sol el administrador
def admin_zone_edit_user(request,user_id):
		profile = UserProfile.objects.get(id=user_id)
		if request.method =='POST':
			form = ProfileForm(profile,request.POST)
			if form.is_valid():
				#Agafem les dades
				un = form.cleaned_data['username']
				e = form.cleaned_data['email']
				pas = form.cleaned_data['password']
				pro = form.cleaned_data['province']
				cp = form.cleaned_data['cp']
				#Comprovem que s'han replenat tots els forms.
				owner = User.objects.get(username=un)
				if un:
					owner.username = un
					profile.username = un
				if e:
					owner.email = e
					profile.email = e
				if pas:
					owner.set_password( pas)
					profile.password = pas
				if pro:
					profile.province = pro
				if cp:
					profile.postalnumber = cp
				#Guadem dades
				profile.save()
			
				return redirect('admin_zone_user_list')
		else:
			form = ProfileForm(profile)
		return render(request,'admin/admin_zone_edit_user.html',{'form': form })	
#Aquesta view s'encarrega de eliminar el usuaris, sol el administrador		
def admin_zone_eliminate_user(request,user_id):
			pu = Publish.objects.filter(id__in=user_id)
			if pu:
				pu.delete()
			u = UserProfile.objects.get(id__in=user_id)
			
			if u:
				own = User.objects.get(username=u.username)
				u.delete()
				own.delete()
			return redirect('admin_zone_user_list')
#Mostra una llista de usuaris registrats			
def admin_zone_user_list(request):
	users = UserProfile.objects.filter()
	return render(request,'admin/admin_zone_user_list.html',{'users':users})
#S'encarrega de crear productes com a administrador	
def admin_zone_create_product(request):
	if request.method=='POST':
		form = ProductForm(request.POST,request.FILES)
		if form.is_valid():
			#Agafem les dades
			n= form.cleaned_data.get('name')
			img = form.cleaned_data.get('image')
			desc = form.cleaned_data.get('description')
			p = form.cleaned_data.get('price')
			ca = form.cleaned_data.get('category')
			cat = Category.objects.get(name=ca)
			#Construir una nova instancia de producte.
			new_data = Product.objects.create(name=n, description=desc, price = p)
			#Pujem les fotos
			for count,x in enumerate(request.FILES.getlist('image')):
				handle_uploaded_file(x,str(x))
				Images.objects.create(post=new_data, image=str(x))
			Owns.objects.create(category=cat, product=new_data)
			#Guardem les dades
			new_data.save()
			messages.info(request, 'Three credits remain in your account.')
			return redirect('product_list')
	else:
		form = ProductForm()		
	return render(request,'admin/admin_zone_create_product.html',{'form': form,})
#S'encarrega de editar la informacio dels productes com a administrador	
def admin_zone_edit_product(request,product_id):
		#Busquem el producte a editar
		product = Product.objects.get(id=product_id)
		if request.method =='POST':
			form = ProductEditForm(product,request.POST)
			if form.is_valid():
				#Agafem les dades
				un = form.cleaned_data['name']
				des = form.cleaned_data['description']
				pr = form.cleaned_data['price']
				ca = form.cleaned_data['category']
				isb= form.cleaned_data['is_buyed']
				#Comprovem el camps que s'han cambiat.
				if un:
					product.name = un
				if des:
					product.description = des
				if pr:
					product.price = pr
				if ca:
					product.category = ca

					
				product.is_buyed = isb
				
				#Guardem les dades
				product.save()
				
				return redirect('product_list')
		else:
			form = ProductEditForm(product)
		return render(request,'admin/admin_zone_edit_product.html',{'form': form })
		
#S'encarrega de eliminar productes com a administrador.
def admin_zone_eliminate_product(request,product_id):
			#Busquem les dades a elimninar i les borrem de la base de dades
			ow = Owns.objects.filter(product_id=product_id)
			if ow:
				ow.delete()
			pu = Publish.objects.filter(product_id=product_id)
			if pu:
				pu.delete()
			i = Images.objects.filter(post_id=product_id)
			if i:
				i.delete()
			p = Product.objects.filter(id=product_id)
			if p:
				p.delete()
			return redirect('product_list')
#Mostre una llista de productes registrats.			
def admin_zone_product_list(request):
	products = Product.objects.filter()
	return render(request,'admin/admin_zone_product_list.html',{'products':products})
	
	
#def admin_zone_create_payments(request):
def admin_zone_edit_payments(request,payment_id):
		pay = Pay.objects.get(id=payment_id)
		if request.method =='POST':
			form = ProductEditForm(pay,request.POST)
			if form.is_valid():
				un = form.cleaned_data['name']
				des = form.cleaned_data['description']
				pr = form.cleaned_data['price']
				ca = form.cleaned_data['category']
				isb= form.cleaned_data['is_buyed']
				print isb
				if un:
					product.name = un
				if des:
					product.description = des
				if pr:
					product.price = pr
				if ca:
					product.category = ca

					
				product.is_buyed = isb
				
					
				product.save()
				
				return redirect('product_list')
		else:
			form = ProductEditForm(product)
		return render(request,'admin/admin_zone_edit_product.html',{'form': form })
		
#def admin_zone_eliminate_payments(request):
def admin_zone_payments_list(request):
		payments = Pay.objects.filter()
		return render(request,'admin/admin_zone_payment_list.html',{'payments':payments})
#def admin_zone_create_category(request):
#def admin_zone_edit_category(request):
#def admin_zone_eliminate_category(request):
#def admin_zone_category_list(request):

#S'encarrega de procesar les cerques de usuari
def buscar(request):
	print request.POST
	if request.method =='POST':
		form = Consultaform(request.POST)
		form2 = Filtresform(request.POST)
		args ={}
		if form.is_valid():
			#Agafem les dades introduides als inputs
			data = form.cleaned_data['consulta']
			cat = form.cleaned_data['provincia']
			#Busquem productes a partir de les dades donades.
			resu = Product.objects.filter(Q(name__icontains=data)|Q(description__contains=data)).order_by('-data')
			res = UserProfile.objects.filter(province__icontains=cat).values('username')
			res2  = Publish.objects.filter(user__in=res)
			
			#Comprovem que hagi dades a mostrar
			if  res2:
				args ={'form':form,'form2':form2,'text':data,'result':res2,'user':res}
			if res:
				args ={'form':form,'form2':form2,'text':data,'result':resu,'user':res}
					
			

		
		#Retorne a la pagina on mostrara el productes.
		return render(request,'resultats_consulta.html',args)
	else:
		form = Consultaform()
		form2 = Filtresform()

		return render(request, 'category.html',)
#Permet afegir productes al carro
def cart_add(request,product_id):
	if request.method=='POST':
		#Busquem el producte per introduir al carro
		cart = Cart(request)
		product = get_object_or_404(Product,id=product_id)
		form = CartAddProductForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			#Afegim les dades del producte.Per saber com funcione el carro mirar cart.py.
			cart.add(product=product,quantity=1,update_quantity=cd['update'])
		return redirect('/cart')
#Permet eliminar productes del carro		
def cart_remove(request,product_id):
	cart = Cart(request)
	product = get_object_or_404(Product,id=product_id)
	cart.remove(product)
	return redirect('/cart')
	
#Mostra el contingut del carro
@login_required(login_url='login')
def cart_list(request):
	cart = Cart(request)
	return render(request,'cart.html',{'cart':cart})
	

#Permet crear productes com a usuari
@login_required(login_url='login')
def create_product(request):
	#dataset = Product.objects.filter(id=id)[0]
	if request.method=='POST':
		print "POST-Create_product"
		form = ProductForm(request.POST,request.FILES)

tenda/templates/anunci.html
<html>
  <head>
    <title></title>
    <meta content="">
    <style></style>
  </head>
  <body><div>Rummi</div>
  <div><ul>
  <a href="/ajuda">Ajuda</a>
  <a href="/anunci" >Anuncis</a>
  <a href="/crear_anuncis" >Crear anuncis</a>
  <a href="/login" >Iniciar sessio</a>
  </ul></div>
  <div><form action="">
	  <input type="text"></input>
	  <select></select>
	  <input type="submit" value="Buscar"></input>
  </form></div>
  <div>Anuncis

  </div></body>
</html>

tenda/templates/cart.html
{% extends 'index.html'%}
{% load staticfiles %}
{%block content%}
<h1>El teu carrito</h1>
<table>
	<thead>
	<tr>
		<th>Imatge</th>
		<th>Producte</th>
		
		<th>Borrar</th>
		<th>Preu </th>
		
	</tr></thead>
	<tboby>
	{%for item in cart%}
	{%with product=item.product%}
	<tr>
		<td>
			<a href="/product/{{product.id}}"><img src="{% static product.images_set.all.0.image.url %}" width="50px" height="100px"></img></a>
		</td>
		<td>{{product.name}}</td>
		
		<td><a href="{% url 'cart_remove' product.id%}">Borrar</a>
		</td>
		<td>{{item.price}}</td>
		
		
	</tr>
		{% endwith %}
	{% endfor %}
	<tr>
	<td>Total</td>
	<td> 
</td>
	<td>{{cart.get_total_price}}</td>
	</tr>
	</tboby>
</table>
<h2>Pas 1: Confirmació de la compra</h2>
<div id ="logout">
	<a href="/payment">
	<input type="submit" value="Tramitar comanda"></input>
    </a>
  </div>
{%endblock%}  

tenda/templates/category.html
{% extends 'index.html'%}
{%block content%}
<div class="categori">Categories
<ul>
  <a href="/search_category?query_name={{ 1 }}" value="1">Vehicles</a>
  <a href="/search_category?query_name={{ 2 }}" value="2">Inmobles</a>
  <a href="/search_category?query_name={{ 3 }}" value="3">Mobles</a>
  <a href="/search_category?query_name={{ 4 }}" value="4">Moda</a>
  <a href="/search_category?query_name={{ 5 }}" value="5">Nens</a>
  <a href="/search_category?query_name={{ 6 }}" value="6">Electrónica</a>
  </ul>
  <ul>
  <a href="/search_category?query_name={{ 7 }}" value="7">Mascotes</a>
  <a href="/search_category?query_name={{ 8 }}" value="8">Treball i formació</a>
  <a href="/search_category?query_name={{ 9 }}" value="9">Esports</a>
  <a href="/search_category?query_name={{ 10 }}" value="10">Negocis i serveis</a>
  <a href="/search_category?query_name={{ 11 }}" value="11">Altres</a>
  </ul>
  </div>
  
{%endblock%} 

tenda/templates/crear_anunci.html
<html>
  <head>
    <title></title>
    <meta content="">
    <style></style>
  </head>
  <body></body>
</html>

tenda/templates/index.html
{% load staticfiles %}
 
<html>
  <head>
    <title>Rummi</title>
    <meta content="">
    <style></style>
    
    <link rel="stylesheet" href="{% static 'css/style.css'%}"></link>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>
  <body>
	  <div id="title">Rummi</div>
  <div id="nav"><ul>
		<a href="/ajuda">Ajuda</a>
		<a href="/">Inici</a>
		
  <a href="/create_product" >Crear anuncis</a>
   <a href="/product_list" >Els teus anuncis</a>
   <a href="/tickets" >Comandes rebudes</a>
  {%if not request.user.is_authenticated %} 
  <a href="/login" >Iniciar sessio</a>
  <a href="/registre" >Crea compte</a>
  {%else%}
  <a href="/logout" >Tancar sessio</a>
  <a href="/profile" >Editar perfil</a>
  {%endif%}
  {%if request.user.is_superuser%}
  <ul class="nav">
  <li ><a href="/admin" >Admin zone</a>
		<ul>
							<li><a href="">ProductsZone</a></li>
							<li><a href="">PaymentsZone</a></li>
							<li><a href="">UserZone</a></li>
							<li><a href="">CategoryZone</a></li>
	     </ul>
	</li>
  </ul>
  {%endif%}
  <a href="/cart" >Carro({{  request.session.cart|length }})</a>
  </ul></div>
  <div id="search"><form action="{% url 'buscar'%}" method="post">
	  {% csrf_token %}
	  <input type="text" name="consulta"></input>
	  <select name="provincia">
		  <option value="">Provincia...</option>
<option value="a coruña">A coru&#241;a</option>
<option value="alava">&#193;lava</option>
<option value="albacete">Albacete</option>
<option value="alicante">Alicante</option>
<option value="almeria">Almer&#237;a</option>
<option value="asturias">Asturias</option>
<option value="avila">&#193;vila</option>
<option value="badajoz">Badajoz</option>
<option value="baleares">Baleares</option>
<option value="barcelona">Barcelona</option>
<option value="burgos">Burgos</option>
<option value="caceres">C&#225;ceres</option>
<option value="cadiz">C&#225;diz</option>
<option value="cantabria">Cantabria</option>
<option value="castellon">Castell&#243;n</option>
<option value="ceuta">Ceuta</option>
<option value="ciudad real">Ciudad Real</option>
<option value="cordoba">C&#243;rdoba</option>
<option value="cuenca">Cuenca</option>
<option value="extranjero">Extranjero</option>
<option value="girona">Girona</option>
<option value="granada">Granada</option>
<option value="guadalajara">Guadalajara</option>
<option value="guipuzcoa">Guip&#250;zcoa</option>
<option value="huelva">Huelva</option>
<option value="huesca">Huesca</option>
<option value="jaen">Ja&#233;n</option>
<option value="la rioja">La rioja</option>
<option value="las palmas">Las palmas</option>
<option value="leon">Le&#243;n</option>
<option value="lleida">Lleida</option>
<option value="lugo">Lugo</option>
<option value="madrid">Madrid</option>
<option value="malaga">M&#225;laga</option>
<option value="melilla">Melilla</option>
<option value="murcia">Murcia</option>
<option value="navarra">Navarra</option>
<option value="ourense">Ourense</option>
<option value="palencia">Palencia</option>
<option value="pontevedra">Pontevedra</option>
<option value="salamanca">Salamanca</option>
<option value="santa cruz de tenerife">Santa cruz de tenerife</option>
<option value="segovia">Segovia</option>
<option value="sevilla">Sevilla</option>
<option value="soria">Soria</option>
<option value="tarragona">Tarragona</option>
<option value="teruel">Teruel</option>
<option value="toledo">Toledo</option>
<option value="valencia">Valencia</option>
<option value="valladolid">Valladolid</option>
<option value="vizcaya">Vizcaya</option>
<option value="zamora">Zamora</option>
<option value="zaragoza">Zaragoza</option>
	  </select>
	  <input type="submit" value="Buscar"></input>
  </form></div>
  <div id ="container">
	  <div id="right_column"></div>
	  <div id ="center_column">
		  
		  {% block content %}
    {% endblock %}
	  </div>
	  <div id="right_column"></div>
  </div> 
   <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

tenda/templates/iniciar_sessio.html
{% extends 'index.html'%}
{%block content%}
 <h2>Iniciar sessio</h2>
  <div><form id="login"action="{% url 'login'%}" method ="post">
		{% csrf_token %}
		{{form.as_p}}
		
		<input type="submit" value="Login"></input>

  </form></div>
{%endblock%}

tenda/templates/logout.html
{% extends 'index.html'%}
{%block content%}
<h1>Tancar sessio</h1>

  <div><form id="logout" action="{% url 'logout'%}" method ="post">
		{% csrf_token %}
		
		<input type="submit" value="Logout"></input>

  </form></div>
{%endblock%} 

tenda/templates/payment_last.html
{% extends 'index.html'%}
{%block content%}

<h2>Pas3: Metode de pagament</h2>
  <div id ="logout">
		<p>Destinatari:{{user.username}}</p>
	    <p>Adreça:{{adress}}</p>
	    <p>Ciutat/població:{{city}}</p>
	    <p>Provincia:{{province}}</p>
	    <p>Codi postal:{{codipostal}}</p>
		{% csrf_token %}
		{{form2.render}}
		
	

 </div>



{%endblock%}    

tenda/templates/registre_usuari.html
{% extends 'index.html'%}
{%block content%}
<div id="right_column"></div>
<h2>Registre d'usuari</h2>
  <div ><form id="login"action="{% url 'registre'%}" method ="post">
		{% csrf_token %}
		{{form.as_p}}
		
		<input type="submit" value="Registra"></input>

  </form></body>
{%endblock%}

tenda/templates/resultats_consulta.html
{%extends 'index.html'%}
{% load staticfiles %}
{% csrf_token %}

  {% block content %}
	<div>Filtres
		<form action="{% url 'filtra'%}" method ="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{form2.as_p}}
		<input type="submit" value="Filtra"></input>

	</div>
  <div>
	  
  {%for i in result%}
  {% if i.is_buyed%}
  {%else%}
   <div id="block">
  <center>
		<img src="{% static i.images_set.all.0.image.url %}" width="150px" height="200px"></img>
  
  </center>
  <a href="/product/{{i.id}}">{{i.name}}</a>
  
  <p>{{i.price}}€</p>
  <p>{{i.data}}</p>

     </div>
   {%endif%}
  
  {%endfor%}

  </div>
  {% endblock %}

tenda/templates/success_payment.html
 

{%extends 'index.html'%}
{% load staticfiles %}
  {% block content %}
  
  <h2>Pagament rebut</h2>
  <p id ="logout"> La teva compra s'ha realitzat amb exít.</p>
  {% endblock %}

tenda/templates/tickets_list.html
{% extends 'index.html'%}
{% load staticfiles %}
{%block content%}
<h1>Comandes rebudes</h1>
<table>
	<thead>
	<tr>
		
		<th>Data</th>

		<th>Adreça</th>
		<th>Ciutat/Població</th>
		<th>Preu </th>
		
		
	</tr></thead>
	<tboby>
	{%for item in bill%}
	
	<tr>
	
		<td>{{item.data}}</td>
		<td>{{item.adress}}</td>
		<td>{{item.city}}</td>

		<td>{{item.total}}</td>
		
		
	</tr>

	{% endfor %}
	
	</tboby>
</table>
{%endblock%}

tenda/templates/unsuccess_payment.html
{%extends 'index.html'%}
{% load staticfiles %}
  {% block content %}
  <p id ="logout"> La teva compra no s'ha pogut completar.</p>
  <p>Torna a intentarhu o crida a un administrador</p>
  {% endblock %}